### ISSUE TITLE
Feature flags are reset upon refresh (1.5.0)

### ISSUE THREAD

**Issue by timbunch** [mjt01/angular-feature-flags#44] opened 2017-01-26 19:51 UTC
After updating to 1.5.0, feature flag settings are reset when the page is refreshed. As long as someone stays within the SPA, everything is good.

**Comment by mjt01** [comment] 2017-01-26 21:55
That is intended behaviour I would've thought. Resetting to initial state plus local overrides. Can you clarify what is not working for you?

**Comment by timbunch** [comment] 2017-01-27 14:27
Sure. The local overrides are failing upon refresh and the initial state is invoked. We use feature flags for testing new features as well as providing power users additional options. Those power users are using the feature flag to maintain their preferences, as well as test new features. They find it very frustrating to have to set the feature flags every visit.

**Comment by kjots** [comment] 2017-01-31 05:50
The overrides in local storage are overwritten whenever a new set of feature flags are loaded (See [featureFlags.provider.js#L26](https://github.com/mjt01/angular-feature-flags/blob/v1.5.0/src/featureFlags.provider.js#L26)).  This means that overrides are only effective during a single session of an application - as soon as the app is refreshed and the feature flags are reloaded, the overrides are again reset to the retrieved values.

The use of local storage suggests that overrides are intended to be persistent between refreshes.  If this is not the case then the overrides might as well be stored in an Angular value.

Reverting to 1.4.0 resolves this issue and allows overrides to persist between refreshes as expected.

**Comment by mjt01** [comment] 2017-01-31 11:52
Resolved in v1.6.0. I rolled back the changes in v1.5.0 as after reviewing with the feedback in mind it became obvious that it was breaking the assumption that local overrides always win. Sorry for any inconvenience.

**Closed by mjt01** 2017-01-31 11:52 UTC
